### ISSUE TITLE
fy23_nga_task1

### ISSUE THREAD

**Issue by mperrinel** [NexGenAnalytics/kokkos-kernels#4]
This task aims to track the work to do in order to improve the CMake logic implemented in Kokkos Kernels' build system

- [ ] Aggregate initial info and summarise current state of CMake in order to provide a plan for the CMake improvement

- [ ] Update the CMake logic of rocm TPLs (rocBLAS and rocSPARSE) in the build system to detect installation properties through CMake target configuration instead of the current approach that relies on library path detect by configure option or environment variables.

- [ ] Similarly, the logic for the Intel library MKL needs to be update in the build system to detect the new oneMKL library properly and manage its targets to enable functionalities for both CPU and GPU.

- [ ] The updated CMake logic will be tested in standalone and Trilinos builds, new configuration options will be updated in Kokkos Kernels cm_generate_makefile and test_all_sandia scripts.

**Comment by mperrinel** [comment]
In order to enable rocBLAS, I decided to create a docker container based on the rocm/dev-ubuntu-20.04 image. That permits to have immediately a regular and maintained installation of ROCm.

**Comment by fnrizzi** [comment]
closing this beause superseeded by the project https://github.com/orgs/NexGenAnalytics/projects/5
